# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: janus

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: janus
    main: ./cmd/janus
    binary: janus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - config.example.yaml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*feat(\(.+\))?:.*$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*fix(\(.+\))?:.*$'
      order: 1
    - title: Documentation
      regexp: '^.*docs(\(.+\))?:.*$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^test:"

release:
  github:
    owner: cesc1802
    name: migration-tool
  draft: true
  prerelease: auto
  name_template: "v{{ .Version }}"
  extra_files:
    - glob: scripts/install.sh
    - glob: scripts/install.ps1

  header: |
    ## Migration Tool {{ .Version }}

    ### Quick Install

    **Linux/macOS:**
    ```bash
    curl -fsSL https://github.com/cesc1802/migration-tool/releases/download/v{{ .Version }}/install.sh | sh
    ```
    
    **Windows (PowerShell):**
    ```powershell
    irm https://github.com/cesc1802/migration-tool/releases/download/v{{ .Version }}/install.ps1 | iex
    ```

    ### Manual Installation

    Download the appropriate binary for your platform below.

    **Verify checksum:**
    ```bash
    sha256sum -c checksums.txt --ignore-missing
    ```
  footer: |
    ---
    Full Changelog: https://github.com/cesc1802/migration-tool/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: true
